language: scala
sudo: required

env:
  - TRAVIS_NODE_VERSION="6.2.1"
  
scala:
  - 2.11.7

jdk:
  - oraclejdk8
  
before_script:
  - curl -L -o coursier https://git.io/vgvpD && chmod +x coursier
  
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install

script: 
  - sbt test
  - sbt run
  
